name: motogo_mx
description: GA MotoGo MX — movilidad premium y accesible
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ga_motogo_hero.svg
